# This file was generated by GoReleaser. DO NOT EDIT.
class GkeScale2 < Formula
  desc "gke-scale2 allow you to quickly scale k8s cluster in google cloud"
  homepage "https://github.com/BESTSELLER/gke-scale2"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/BESTSELLER/gke-scale2/releases/download/v0.0.3/gke-scale2_0.0.3_darwin_amd64.zip"
    sha256 "e23e6182ea5c1297f9ab99f695a8d359c6a11929292f9295cb817849bf6f57e5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/BESTSELLER/gke-scale2/releases/download/v0.0.3/gke-scale2_0.0.3_linux_amd64.zip"
      sha256 "8eaba8d2c8cecbb291cef395e79a4020fba089ded667d13c298f225ef52f72cf"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BESTSELLER/gke-scale2/releases/download/v0.0.3/gke-scale2_0.0.3_linux_arm64.zip"
        sha256 "399902ac4fa908e01b99273e2b67ccbabeeb1a60216b7c4d6016edd3256a077c"
      else
      end
    end
  end

  def install
    bin.install "gke-scale2"
  end
end
