# This file was generated by GoReleaser. DO NOT EDIT.
class GkeScale2 < Formula
  desc "gke-scale2 allow you to quickly scale k8s cluster in google cloud"
  homepage "https://github.com/BESTSELLER/gke-scale2"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/BESTSELLER/gke-scale2/releases/download/v0.0.3/gke-scale2_0.0.3_darwin_amd64.zip"
    sha256 "46e56e03a412bcbe21d4ff1d2d5304543fc7ce0374df599b0a1565415acfb4bb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/BESTSELLER/gke-scale2/releases/download/v0.0.3/gke-scale2_0.0.3_linux_amd64.zip"
      sha256 "396114c3cc85675be6538cf13c6da3c216a2744da4aad1ff9f98c9091e08d63d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/BESTSELLER/gke-scale2/releases/download/v0.0.3/gke-scale2_0.0.3_linux_arm64.zip"
        sha256 "6654a9205216b03e5a869214b042edf840ae9f9e40c3f5226dc80c644d9f36ab"
      else
      end
    end
  end

  def install
    bin.install "gke-scale2"
  end
end
